*** Variables ***
${txt_USER}          document.querySelector("sankhya-login").shadowRoot.querySelector("input#user")
${txt_PASSWORD}      document.querySelector("sankhya-login").shadowRoot.querySelector("input#password")
${BTN_PROSSEGUIR}    document.querySelector("sankhya-login").shadowRoot.querySelector("Button.account-btn")
${TXT_ERRO}          document.querySelector("Sankhya-login").shadowRoot.querySelector('div.ant-form-item-control-input-content p')


